---
version: '2.4'

services:
  camunda:
    container_name: camunda
    image: camunda/camunda-bpm-platform:7.20.0-alpha1
    ports:
      - 9404:8080
    networks:
      - ccd-network

networks:
  ccd-network:
    external: true
