version: '2.4'
services:
  cmc-ccd-definition-importer:
    image: hmctspublic.azurecr.io/cmc/ccd-definition-importer:${CMC_CCD_DEFINITION_VERSION:-1.10.36-alpha}
    environment:
      - VERBOSE=${VERBOSE:-false}
      - WAIT_HOSTS=ccd-user-profile-api:4453, ccd-definition-store-api:4451, service-auth-provider-api:8080, ccd-api-gateway:3453, idam-api:5000
      - WAIT_HOSTS_TIMEOUT=900
      - IMPORTER_USERNAME=ccd.docker.default@hmcts.net
      - IMPORTER_PASSWORD=Password12!
      - CCD_STORE_BASE_URL=http://ccd-definition-store-api:4451
      - IDAM_URI=http://idam-api:5000
      - AUTH_PROVIDER_BASE_URL=http://service-auth-provider-api:8080
      - VERBOSE=true
      - MICROSERVICE=ccd_gw
      - REDIRECT_URI=https://localhost:3000/receiver
      - CLIENT_ID=cmc_citizen
      - CLIENT_SECRET=12345678
      - CCD_DEF_FILENAME=cmc-ccd.xlsx
      - CCD_DEF_CLAIM_STORE_BASE_URL=${CLAIM_STORE_URL:-http://claim-store-api:4400}
      - IDAM_KEY_AM_ROLE_ASSIGNMENT=AAAAAAAAAAAAAAAA
      - USER_ROLES=citizen, caseworker-cmc, caseworker-cmc-solicitor, caseworker-cmc-systemupdate, letter-holder, caseworker-autotest1, caseworker-cmc-judge, caseworker-cmc-legaladvisor, caseworker-cmc-anonymouscitizen, caseworker-cmc-pcqextractor, payments
    networks:
      - ccd-network

networks:
  ccd-network:
    external: true

